import type { TFunction } from "i18next";

export const MENU_KEYS = [
  "menu_file",
  "menu_new",
  "menu_edit",
  "menu_insert",
  "menu_format",
  "menu_view",
  "menu_git",
  "menu_window",
  "menu_help",
  "about_item",
  "about_title",
  "about_body",
  "file_new_post",
  "file_new_flow",
  "file_new_note",
  "file_new_series",
  "file_new_book",
  "file_new_page",
  "file_today_flow",
  "file_open_workspace",
  "file_switch_workspace",
  "file_save",
  "file_close_file",
  "edit_find_in_workspace",
  "edit_open_quickly",
  "insert_link",
  "insert_image",
  "insert_code_block",
  "insert_table",
  "insert_hr",
  "format_bold",
  "format_italic",
  "format_strikethrough",
  "format_inline_code",
  "format_heading_1",
  "format_heading_2",
  "format_heading_3",
  "format_heading_4",
  "format_heading_5",
  "format_heading_6",
  "format_blockquote",
  "format_bullet_list",
  "format_ordered_list",
  "format_task_list",
  "format_markdown",
  "view_toggle_sidebar",
  "view_toggle_properties",
  "view_zen_mode",
  "view_typewriter_mode",
  "view_toggle_spell_check",
  "git_commit",
  "git_switch_branch",
  "git_new_branch",
  "git_open_remote",
  "git_copy_remote_url",
  "git_push",
  "git_pull",
  "git_fetch",
  "help_check_updates",
  "help_docs",
  "help_issues",
] as const;

export function buildMenuLabels(t: TFunction): Record<string, string> {
  return Object.fromEntries(MENU_KEYS.map((key) => [key, t(`menu.${key}`)]));
}
